import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PageHeader from "@/app/components/PageHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Parallel Universe Archive",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="absolute inset-0 bg-no-repeat bg-auto bg-right-top body-gr-bg z-0"></div>
        <PageHeader />
        <main className="flex min-h-screen flex-col items-start justify-start px-12 py-12 relative z-10">
          {children}
        </main>
      </body>
    </html>
  );
}
