import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import bodyBgGradient from "@/app/assets/images/body-bg-gradient.png";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Parallel Universe Archive",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="absolute inset-0 bg-no-repeat bg-auto bg-right-top body-gr-bg z-0"></div>
        <header className="w-full flex justify-start items-center p-4 relative z-10">
          <span>Parallel Universe Archive</span>
          <nav className="ms-auto flex justify-start items-center gap-2">
            <Link href="/">Recommendations</Link>
            <Link href="/queue">Queue to play </Link>
          </nav>
        </header>
        <main className="flex min-h-screen flex-col items-start justify-start px-4 py-12 relative z-10">
          {children}
        </main>
      </body>
    </html>
  );
}
